name: hpcdigital
description: "Hinário Digital Hosana – HPC Digital com painel admin desktop"
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

  # 🔥 FlutterFire
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  firebase_app_check: ^0.4.1+1

  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.20.0
  table_calendar: ^3.0.9
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.6.1
  geocoding: ^4.0.0
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_localizations:
    sdk: flutter
  cloud_functions: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4   # 👉 coloque em dev_dependencies
  msix: ^3.16.7

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png             # 👉 garanta que existe
    - images/splashscreen.png     # (se for usar)
    - images/icon.png             # (remova se não usar este caminho)

  fonts:
    - family: NotoMusic
      fonts:
        - asset: assets/fonts/NotoMusic-Regular.ttf

# 👉 Config do gerador de ícones
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"                 # ícone base (1024x1024, sem alpha)
  adaptive_icon_background: "#ffffff"           # fundo (Android)
  adaptive_icon_foreground: "assets/icon.png"   # pode usar igual ou um foreground separado
  remove_alpha_ios: true                        # útil para evitar problemas no iOS
