// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY5XiDRceLqCdMlt2M4FbkTphtEKXUtGI',
    appId: '1:7719808461:web:feb8c3b050874fe71f2884',
    messagingSenderId: '7719808461',
    projectId: 'hpcmobile-9ec3e',
    authDomain: 'hpcmobile-9ec3e.firebaseapp.com',
    storageBucket: 'hpcmobile-9ec3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc-iC1W5s6ThBMdWb8CAqmf7OymxyAhgM',
    appId: '1:7719808461:android:4f489d0c5d5eef121f2884',
    messagingSenderId: '7719808461',
    projectId: 'hpcmobile-9ec3e',
    storageBucket: 'hpcmobile-9ec3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbAXfErVKH5y2yA8AAl9kacvPmRyOEcaM',
    appId: '1:7719808461:ios:473fb355e02114181f2884',
    messagingSenderId: '7719808461',
    projectId: 'hpcmobile-9ec3e',
    storageBucket: 'hpcmobile-9ec3e.firebasestorage.app',
    iosBundleId: 'com.example.hpcdigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbAXfErVKH5y2yA8AAl9kacvPmRyOEcaM',
    appId: '1:7719808461:ios:473fb355e02114181f2884',
    messagingSenderId: '7719808461',
    projectId: 'hpcmobile-9ec3e',
    storageBucket: 'hpcmobile-9ec3e.firebasestorage.app',
    iosBundleId: 'com.example.hpcdigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY5XiDRceLqCdMlt2M4FbkTphtEKXUtGI',
    appId: '1:7719808461:web:bb4c8dfbc4c61fa61f2884',
    messagingSenderId: '7719808461',
    projectId: 'hpcmobile-9ec3e',
    authDomain: 'hpcmobile-9ec3e.firebaseapp.com',
    storageBucket: 'hpcmobile-9ec3e.firebasestorage.app',
  );

}